### ISSUE TITLE
OSError: No such file or directory

### ISSUE THREAD

**Issue by danyfire** [letorbi/synoindexwatcher#45] opened 2020-12-15 19:39 UTC
Hello,

I keep getting a error after I did the command "python -m synoindexwatcher" can you help me  :
I started doing the installation stuff :

```
wget https://bootstrap.pypa.io/get-pip.py -qO - | sudo python
sudo python -m pip install --upgrade synoindexwatcher
python -m synoindexwatcher
```
synoindexwatcher doesn't start I tried with 2 admin accounts :-(

```
_mersaine@Homeland:~$ python -m synoindexwatcher
2020-12-15 20:23:01,638 INFO Adding watch for path: /volume1/music
2020-12-15 20:23:01,639 ERROR An uncaught exception occurred
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/synoindexwatcher/__main__.py", line 206, in <module>
    start()
  File "/usr/lib/python2.7/site-packages/synoindexwatcher/__main__.py", line 176, in start
    inotify.add_watch_recursive(path, mask, filter)
  File "/usr/lib/python2.7/site-packages/inotifyrecursive/inotifyrecursive.py", line 116, in add_watch_recursive
    return self.__add_watch_recursive(path, mask, filter, name, -1, False)
  File "/usr/lib/python2.7/site-packages/inotifyrecursive/inotifyrecursive.py", line 79, in __add_watch_recursive
    wd = inotify_simple.INotify.add_watch(self, path, mask | flags.IGNORED | flags.CREATE | flags.MOVED_FROM | flags.MOVED_TO)
  File "/usr/lib/python2.7/site-packages/inotify_simple.py", line 110, in add_watch
    return _libc_call(_libc.inotify_add_watch, self.fileno(), fsencode(path), mask)
  File "/usr/lib/python2.7/site-packages/inotify_simple.py", line 39, in _libc_call
    raise OSError(errno, os.strerror(errno))
OSError: [Errno 2] No such file or directory_
```

Help me please. I don't understand I'm not a expert.
Danyfire

**Comment by danyfire** [comment] 2020-12-15 19:47
A user in a other post advised me that : 

>_Well, i guess this issue should be placed in https://github.com/letorbi/synoindexwatcher ;)
>
>AFAIR this was caused by an regression in inotify_simple 1.3.2, which was fixed with version 1.3.3. Please upgrade inotify_simple and inotifyrecursive to the latest versions with the following commands:
>```
>sudo python -m pip install --upgrade inotify_simple
>sudo python -m pip install --upgrade inotifyrecursive
>```
>Please create a new issue in my Synoindex Watcher repo, when the problem persists._

I tried but service still won't start here are the messages :
```
mersaine@192.168.1.6's password:
mersaine@Homeland:~$ sudo python -m pip install --upgrade inotify_simple
Password:
DEPRECATION: Python 2.7 reached the end of its life on January 1st, 2020. Please                                                                                                                                                              upgrade your Python as Python 2.7 is no longer maintained. pip 21.0 will drop s                                                                                                                                                             upport for Python 2.7 in January 2021. More details about Python 2 support in pi                                                                                                                                                             p can be found at https://pip.pypa.io/en/latest/development/release-process/#pyt                                                                                                                                                             hon-2-support pip 21.0 will remove support for this functionality.
Requirement already up-to-date: inotify_simple in /usr/lib/python2.7/site-packag                                                                                                                                                             es (1.3.5)
Requirement already satisfied, skipping upgrade: enum34; python_version < "3.4"                                                                                                                                                              in /usr/lib/python2.7/site-packages (from inotify_simple) (1.1.10)
mersaine@Homeland:~$ sudo python -m pip install --upgrade inotifyrecursive
DEPRECATION: Python 2.7 reached the end of its life on January 1st, 2020. Please                                                                                                                                                              upgrade your Python as Python 2.7 is no longer maintained. pip 21.0 will drop s                                                                                                                                                             upport for Python 2.7 in January 2021. More details about Python 2 support in pi                                                                                                                                                             p can be found at https://pip.pypa.io/en/latest/development/release-process/#pyt                                                                                                                                                             hon-2-support pip 21.0 will remove support for this functionality.
Requirement already up-to-date: inotifyrecursive in /usr/lib/python2.7/site-pack                                                                                                                                                             ages (0.3.5)
Requirement already satisfied, skipping upgrade: inotify-simple>=1.3.5 in /usr/l                                                                                                                                                             ib/python2.7/site-packages (from inotifyrecursive) (1.3.5)
Requirement already satisfied, skipping upgrade: enum34; python_version < "3.4"                                                                                                                                                              in /usr/lib/python2.7/site-packages (from inotify-simple>=1.3.5->inotifyrecursiv                                                                                                                                                             e) (1.1.10)
mersaine@Homeland:~$ python -m synoindexwatcher
2020-12-15 20:44:43,226 INFO Adding watch for path: /volume1/music
2020-12-15 20:44:43,227 ERROR An uncaught exception occurred
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/synoindexwatcher/__main__.py", line 206                                                                                                                                                             , in <module>
    start()
  File "/usr/lib/python2.7/site-packages/synoindexwatcher/__main__.py", line 176                                                                                                                                                             , in start
    inotify.add_watch_recursive(path, mask, filter)
  File "/usr/lib/python2.7/site-packages/inotifyrecursive/inotifyrecursive.py",                                                                                                                                                              line 116, in add_watch_recursive
    return self.__add_watch_recursive(path, mask, filter, name, -1, False)
  File "/usr/lib/python2.7/site-packages/inotifyrecursive/inotifyrecursive.py",                                                                                                                                                              line 79, in __add_watch_recursive
    wd = inotify_simple.INotify.add_watch(self, path, mask | flags.IGNORED | fla                                                                                                                                                             gs.CREATE | flags.MOVED_FROM | flags.MOVED_TO)
  File "/usr/lib/python2.7/site-packages/inotify_simple.py", line 110, in add_wa                                                                                                                                                             tch
    return _libc_call(_libc.inotify_add_watch, self.fileno(), fsencode(path), ma                                                                                                                                                             sk)
  File "/usr/lib/python2.7/site-packages/inotify_simple.py", line 39, in _libc_c                                                                                                                                                             all
    raise OSError(errno, os.strerror(errno))
OSError: [Errno 2] No such file or directory
```

**Comment by letorbi** [comment] 2020-12-15 19:47
Well that "other user" was me - the creator of Synoindex Watcher ;) Does the path */volume1/music* actually exists on your system?

PS: You can use three accents (` ``` `) to mark the beginnig and end of a sourceode or logfile snippet. This makes them a bit more readable.

**Comment by danyfire** [comment] 2020-12-15 19:59
> Well that "other user" was me - the creator of Synoindex Watcher ;) Does the path _/volume1/music_ actually exists on your system?
> 
> PS: You can use three accents (`` ``` ``) to mark the beginnig and end of a sourceode or logfile snippet. This makes them a bit more readable.

Thank you for your answer and explanation, the folder _/volume1/music_ does exist :

![image](https://user-images.githubusercontent.com/7409924/102266234-746d0980-3f18-11eb-8661-23b6452bd157.png)


![image](https://user-images.githubusercontent.com/7409924/102266417-b26a2d80-3f18-11eb-867d-65b20c3d582a.png)

**Comment by letorbi** [comment] 2020-12-15 20:08
Ok, there is a folder named "Music", but the file-system of a DiskStation is case-sensitive. So */volume1/Music* is not equal to */volume1/music*. So the error `No such file or directory` is actually the correct result here.

That said, your problem is a duplicate of #44 and Synoindex Watcher could be smarter here. But for now I recommend to explicitly add the paths you want to watch to the command that starts Synoindex Watcher:

```
$ python -m synoindexwatcher /volume1/Music /volume1/photo /volume1/Video
```

This should solve your problem.

**Comment by danyfire** [comment] 2020-12-15 20:12
Indeed that seems to have fixed the issue thank you so much for your help.
I will finish the installation now

```
mersaine@Homeland:~$ sudo python -m synoindexwatcher /volume1/Music /volume1/photo /volume1/Video
Password:
2020-12-15 21:11:03,764 INFO Adding watch for path: /volume1/Music
2020-12-15 21:11:04,149 INFO Adding watch for path: /volume1/photo
2020-12-15 21:11:04,150 INFO Adding watch for path: /volume1/Video
2020-12-15 21:11:04,396 INFO Waiting for media file changes...
```
What are the commands I need to do, to adjust the script to make sure it starts on Synology boot.
And make sure it takes my folder configuration in consideration.

**Comment by letorbi** [comment] 2020-12-15 20:15
Ok, great :) Just one last note: Synoindex Watcher does not need `sudo` to run. I've added this to the command in my previous post by accident.

**Comment by letorbi** [comment] 2020-12-15 21:07
I've just upgraded Synoindex Watcher so that it shows a better explanation than just printing the exception. Thanks for reporting the issue.

**Comment by danyfire** [comment] 2020-12-15 22:11
> I've just upgraded Synoindex Watcher so that it shows a better explanation that just printing the exception. Thanks for reporting the issue.

You are welcome and thank you for helping me.
I still need to set up the auto boot part, and make sure it takes my folder configuration in consideration.
I suppose I need to edit the configuration file to monitor the right folder names then generate the auto start boot script to use the config file. Working on it. I'm not really good at all this. I understand the explanation in instructions, but I don't understand the command lines...
I suppo I have to use those but I first need to edit the config file :
```
$ python -m synoindexwatcher --generate-init | sudo tee /usr/local/etc/rc.d/S99synoindexwatcher.sh
$ sudo chmod a+x /usr/local/etc/rc.d/S99synoindexwatcher.sh

```

**Comment by letorbi** [comment] 2020-12-16 11:41
You have to add the paths you want to watch to the synoindexwatcher call again:

```
$ python -m synoindexwatcher --generate-init  /volume1/Music /volume1/photo /volume1/Video | sudo tee /usr/local/etc/rc.d/S99synoindexwatcher.sh
$ sudo chmod a+x /usr/local/etc/rc.d/S99synoindexwatcher.sh
```

This should do the trick :) [See the Readme for details.](https://github.com/letorbi/synoindexwatcher#start-on-boot)

**Comment by letorbi** [comment] 2020-12-16 11:44
...or if you want to use a config file:

```
$ python -m synoindexwatcher --generate-config /volume1/Music /volume1/photo /volume1/Video | sudo tee /usr/local/etc/synoindexwatcher.conf
$ python -m synoindexwatcher --generate-init --config=/usr/local/etc/synoindexwatcher.conf | sudo tee /usr/local/etc/rc.d/S99synoindexwatcher.sh
$ sudo chmod a+x /usr/local/etc/rc.d/S99synoindexwatcher.sh
```

[The details are again in the Readme.](https://github.com/letorbi/synoindexwatcher#configuration-file)

**Comment by danyfire** [comment] 2020-12-16 18:32
> ...or if you want to use a config file:
> 
> ```
> $ python -m synoindexwatcher --generate-config /volume1/Music /volume1/photo /volume1/Video | sudo tee /usr/local/etc/synoindexwatcher.conf
> $ python -m synoindexwatcher --generate-init --config=/usr/local/etc/synoindexwatcher.conf | sudo tee /usr/local/etc/rc.d/S99synoindexwatcher.sh
> $ sudo chmod a+x /usr/local/etc/rc.d/S99synoindexwatcher.sh
> ```
> 
> [The details are again in the Readme.](https://github.com/letorbi/synoindexwatcher#configuration-file)

Thank you for your reply, unfortunately the 2nd command generated an error :-( :

`mersaine@Homeland:~$ python -m synoindexwatcher --generate-init --config=/usr/lo                                                                                                                                                             cal/etc/synoindexwatcher.conf | sudo tee /usr/local/etc/rc.d/S99synoindexwatcher                                                                                                                                                             .sh
#!/bin/sh

# This file has been generated by Synoindex Watcher.

ARGS="--config=/usr/local/etc/synoindexwatcher.conf"
PIDFILE="/var/run/synoindexwatcher.pid"

start_synoindexwatcher() {
    if [ ! -f "$PIDFILE" ]; then
        echo "Starting synoindexwatcher..."
        # Set LC_ALL to ensure that the filesystem encoding is correctly
        # detected during boot.
        nohup env LC_ALL=en_US.utf8 /bin/python -m synoindexwatcher $ARGS > /dev                                                                                                                                                             /null 2>&1 &
        echo $! > "$PIDFILE"
    else
        echo "Error: synoindexwatcher has already been started"
        exit 1
    fi
}

stop_synoindexwatcher() {
    if [ -f "$PIDFILE" ]; then
        echo "Stopping synoindexwatcher..."
        kill `cat "$PIDFILE"`
        rm "$PIDFILE"
    else
        echo "Error: synoindexwatcher has not been started yet"
        exit 1
    fi
}

case "$1" in
    start|"")
        start_synoindexwatcher
        ;;
    restart|reload|force-reload)
        stop_synoindexwatcher
        start_synoindexwatcher
        ;;
    stop)
        stop_synoindexwatcher
        ;;
    *)
        echo "Usage: `basename $0` [start|stop]" >&2
        exit 3
        ;;
esac
`

**Comment by danyfire** [comment] 2020-12-16 18:41
> ...or if you want to use a config file:
> 
> ```
> $ python -m synoindexwatcher --generate-config /volume1/Music /volume1/photo /volume1/Video | sudo tee /usr/local/etc/synoindexwatcher.conf
> $ python -m synoindexwatcher --generate-init --config=/usr/local/etc/synoindexwatcher.conf | sudo tee /usr/local/etc/rc.d/S99synoindexwatcher.sh
> $ sudo chmod a+x /usr/local/etc/rc.d/S99synoindexwatcher.sh
> ```
> 
> [The details are again in the Readme.](https://github.com/letorbi/synoindexwatcher#configuration-file)

Thank you for your reply, I tried using the config file commands you suggested.
Unfortunately I'm very unlucky, the 2nd command to configure the boot script generated a new error :-( :

```
mersaine@Homeland:~$ python -m synoindexwatcher --generate-config /volume1/Music /volume1/photo /volume1/Video | sudo tee /usr/local/etc/synoindexwatcher.conf
[GLOBAL]
blacklist=^\.|^\@|\.tmp$
whitelist=
logfile=/var/log/synoindexwatcher.log
loglevel=INFO

[/volume1/Music]

[/volume1/photo]

[/volume1/Video]
mersaine@Homeland:~$ python -m synoindexwatcher --generate-init --config=/usr/local/etc/synoindexwatcher.conf | sudo tee /usr/local/etc/rc.d/S99synoindexwatcher.sh
#!/bin/sh

# This file has been generated by Synoindex Watcher.

ARGS="--config=/usr/local/etc/synoindexwatcher.conf"
PIDFILE="/var/run/synoindexwatcher.pid"

start_synoindexwatcher() {
    if [ ! -f "$PIDFILE" ]; then
        echo "Starting synoindexwatcher..."
        # Set LC_ALL to ensure that the filesystem encoding is correctly
        # detected during boot.
        nohup env LC_ALL=en_US.utf8 /bin/python -m synoindexwatcher $ARGS > /dev/null 2>&1 &
        echo $! > "$PIDFILE"
    else
        echo "Error: synoindexwatcher has already been started"
        exit 1
    fi
}

stop_synoindexwatcher() {
    if [ -f "$PIDFILE" ]; then
        echo "Stopping synoindexwatcher..."
        kill `cat "$PIDFILE"`
        rm "$PIDFILE"
    else
        echo "Error: synoindexwatcher has not been started yet"
        exit 1
    fi
}

case "$1" in
    start|"")
        start_synoindexwatcher
        ;;
    restart|reload|force-reload)
        stop_synoindexwatcher
        start_synoindexwatcher
        ;;
    stop)
        stop_synoindexwatcher
        ;;
    *)
        echo "Usage: `basename $0` [start|stop]" >&2
        exit 3
        ;;
esac
mersaine@Homeland:~$ sudo chmod a+x /usr/local/etc/rc.d/S99synoindexwatcher.sh
mersaine@Homeland:~$

```


LOG /var/log/synoindexwatcher.log : 



```
mersaine@Homeland:~$ vi /var/log/synoindexwatcher.log
2020-05-06 16:49:01,519 INFO Adding watch for path: /volume1/music
2020-05-06 16:49:01,519 ERROR An uncaught exception occurred
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/synoindexwatcher/__main__.py", line 224, in <module>
    start()
  File "/usr/lib/python2.7/site-packages/synoindexwatcher/__main__.py", line 194, in start
    inotify.add_watch_recursive(path, mask, filter)
  File "/usr/lib/python2.7/site-packages/inotifyrecursive/inotifyrecursive.py", line 116, in add_watch_recursive
    return self.__add_watch_recursive(path, mask, filter, name, -1, False)
  File "/usr/lib/python2.7/site-packages/inotifyrecursive/inotifyrecursive.py", line 79, in __add_watch_recursive
    wd = inotify_simple.INotify.add_watch(self, path, mask | flags.IGNORED | flags.CREATE | flags.MOVED_FROM | flags.MOVED_TO)
  File "/usr/lib/python2.7/site-packages/inotify_simple.py", line 105, in add_watch
    return _libc_call(_libc.inotify_add_watch, self.fileno(), fsencode(path), mask)
  File "/usr/lib/python2.7/site-packages/inotify_simple.py", line 38, in _libc_call
    raise OSError(errno, strerror(errno))
OSError: [Errno 2] No such file or directory
2020-05-07 07:01:34,191 INFO Adding watch for path: /volume1/music
2020-05-07 07:01:34,202 ERROR An uncaught exception occurred
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/synoindexwatcher/__main__.py", line 224, in <module>
    start()
  File "/usr/lib/python2.7/site-packages/synoindexwatcher/__main__.py", line 194, in start
    inotify.add_watch_recursive(path, mask, filter)
  File "/usr/lib/python2.7/site-packages/inotifyrecursive/inotifyrecursive.py", line 116, in add_watch_recursive
    return self.__add_watch_recursive(path, mask, filter, name, -1, False)
  File "/usr/lib/python2.7/site-packages/inotifyrecursive/inotifyrecursive.py", line 79, in __add_watch_recursive
    wd = inotify_simple.INotify.add_watch(self, path, mask | flags.IGNORED | flags.CREATE | flags.MOVED_FROM | flags.MOVED_TO)
  File "/usr/lib/python2.7/site-packages/inotify_simple.py", line 105, in add_watch
    return _libc_call(_libc.inotify_add_watch, self.fileno(), fsencode(path), mask)
  File "/usr/lib/python2.7/site-packages/inotify_simple.py", line 38, in _libc_call
    raise OSError(errno, strerror(errno))
OSError: [Errno 2] No such file or directory
2020-05-08 07:01:32,210 INFO Adding watch for path: /volume1/music
2020-05-08 07:01:32,219 ERROR An uncaught exception occurred
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/synoindexwatcher/__main__.py", line 224, in <module>
    start()
  File "/usr/lib/python2.7/site-packages/synoindexwatcher/__main__.py", line 194, in start
    inotify.add_watch_recursive(path, mask, filter)
  File "/usr/lib/python2.7/site-packages/inotifyrecursive/inotifyrecursive.py", line 116, in add_watch_recursive
    return self.__add_watch_recursive(path, mask, filter, name, -1, False)
  File "/usr/lib/python2.7/site-packages/inotifyrecursive/inotifyrecursive.py", line 79, in __add_watch_recursive
    wd = inotify_simple.INotify.add_watch(self, path, mask | flags.IGNORED | flags.CREATE | flags.MOVED_FROM | flags.MOVED_TO)
  File "/usr/lib/python2.7/site-packages/inotify_simple.py", line 105, in add_watch
    return _libc_call(_libc.inotify_add_watch, self.fileno(), fsencode(path), mask)
  File "/usr/lib/python2.7/site-packages/inotify_simple.py", line 38, in _libc_call
    raise OSError(errno, strerror(errno))
OSError: [Errno 2] No such file or directory
2020-05-09 07:01:31,825 INFO Adding watch for path: /volume1/music
2020-05-09 07:01:31,836 ERROR An uncaught exception occurred
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/synoindexwatcher/__main__.py", line 224, in <module>
    start()
  File "/usr/lib/python2.7/site-packages/synoindexwatcher/__main__.py", line 194, in start
    inotify.add_watch_recursive(path, mask, filter)
  File "/usr/lib/python2.7/site-packages/inotifyrecursive/inotifyrecursive.py", line 116, in add_watch_recursive
    return self.__add_watch_recursive(path, mask, filter, name, -1, False)
  File "/usr/lib/python2.7/site-packages/inotifyrecursive/inotifyrecursive.py", line 79, in __add_watch_recursive
    wd = inotify_simple.INotify.add_watch(self, path, mask | flags.IGNORED | flags.CREATE | flags.MOVED_FROM | flags.MOVED_TO)
  File "/usr/lib/python2.7/site-packages/inotify_simple.py", line 105, in add_watch
    return _libc_call(_libc.inotify_add_watch, self.fileno(), fsencode(path), mask)
  File "/usr/lib/python2.7/site-packages/inotify_simple.py", line 38, in _libc_call
            
```

**Comment by letorbi** [comment] 2020-12-16 20:44
Hi again :)

I hope the problem has been fixed with commit 978e47fd6a34676f71b5c31861e535336525e1af and I've just released version 0.11.3, which contains the fix.

Could you please upgrade the *synoindexwatcher* package again and check again? There is no need to generate the config-file or the init-script again.

**Comment by danyfire** [comment] 2020-12-16 21:03
Im not sure what I'm doing wrong I'm having the same problem even after update :

```
mersaine@Homeland:~$ wget https://bootstrap.pypa.io/get-pip.py -qO - | sudo pyth                                                                                                                                                             on
Password:
DEPRECATION: Python 2.7 reached the end of its life on January 1st, 2020. Please                                                                                                                                                              upgrade your Python as Python 2.7 is no longer maintained. pip 21.0 will drop s                                                                                                                                                             upport for Python 2.7 in January 2021. More details about Python 2 support in pi                                                                                                                                                             p can be found at https://pip.pypa.io/en/latest/development/release-process/#pyt                                                                                                                                                             hon-2-support pip 21.0 will remove support for this functionality.
Collecting pip
  Using cached pip-20.3.3-py2.py3-none-any.whl (1.5 MB)
Installing collected packages: pip
  Attempting uninstall: pip
    Found existing installation: pip 20.3.3
    Uninstalling pip-20.3.3:
      Successfully uninstalled pip-20.3.3
Successfully installed pip-20.3.3
mersaine@Homeland:~$ sudo python -m pip install --upgrade synoindexwatcher
DEPRECATION: Python 2.7 reached the end of its life on January 1st, 2020. Please                                                                                                                                                              upgrade your Python as Python 2.7 is no longer maintained. pip 21.0 will drop s                                                                                                                                                             upport for Python 2.7 in January 2021. More details about Python 2 support in pi                                                                                                                                                             p can be found at https://pip.pypa.io/en/latest/development/release-process/#pyt                                                                                                                                                             hon-2-support pip 21.0 will remove support for this functionality.
Requirement already up-to-date: synoindexwatcher in /usr/lib/python2.7/site-pack                                                                                                                                                             ages (0.11.3)
Requirement already satisfied, skipping upgrade: configparser; python_version <                                                                                                                                                              "3.5" in /usr/lib/python2.7/site-packages (from synoindexwatcher) (4.0.2)
Requirement already satisfied, skipping upgrade: inotifyrecursive>=0.3.5 in /usr                                                                                                                                                             /lib/python2.7/site-packages (from synoindexwatcher) (0.3.5)
Requirement already satisfied, skipping upgrade: inotify-simple>=1.3.5 in /usr/l                                                                                                                                                             ib/python2.7/site-packages (from inotifyrecursive>=0.3.5->synoindexwatcher) (1.3                                                                                                                                                             .5)
Requirement already satisfied, skipping upgrade: enum34; python_version < "3.4"                                                                                                                                                              in /usr/lib/python2.7/site-packages (from inotify-simple>=1.3.5->inotifyrecursiv                                                                                                                                                             e>=0.3.5->synoindexwatcher) (1.1.10)
mersaine@Homeland:~$ python -m synoindexwatcher --generate-init --config=/usr/lo                                                                                                                                                             cal/etc/synoindexwatcher.conf | sudo tee /usr/local/etc/rc.d/S99synoindexwatcher                                                                                                                                                             .sh
#!/bin/sh

# This file has been generated by Synoindex Watcher.

ARGS="--config=/usr/local/etc/synoindexwatcher.conf"
PIDFILE="/var/run/synoindexwatcher.pid"

start_synoindexwatcher() {
    if [ ! -f "$PIDFILE" ]; then
        echo "Starting synoindexwatcher..."
        # Set LC_ALL to ensure that the filesystem encoding is correctly
        # detected during boot.
        nohup env LC_ALL=en_US.utf8 /bin/python -m synoindexwatcher $ARGS > /dev                                                                                                                                                             /null 2>&1 &
        echo $! > "$PIDFILE"
    else
        echo "Error: synoindexwatcher has already been started"
        exit 1
    fi
}

stop_synoindexwatcher() {
    if [ -f "$PIDFILE" ]; then
        echo "Stopping synoindexwatcher..."
        kill `cat "$PIDFILE"`
        rm "$PIDFILE"
    else
        echo "Error: synoindexwatcher has not been started yet"
        exit 1
    fi
}

case "$1" in
    start|"")
        start_synoindexwatcher
        ;;
    restart|reload|force-reload)
        stop_synoindexwatcher
        start_synoindexwatcher
        ;;
    stop)
        stop_synoindexwatcher
        ;;
    *)
        echo "Usage: `basename $0` [start|stop]" >&2
        exit 3
        ;;
esac
mersaine@Homeland:~$

```

**Comment by danyfire** [comment] 2020-12-17 08:05
Hello I think I managed to find a workaround to make things work. Instead of trying to make a autoboot script, I added the command : `python -m synoindexwatcher /volume1/Music /volume1/photo /volume1/Video /volume1/Incoming` 
in the Task scheduler of Synology :

![image](https://user-images.githubusercontent.com/7409924/102460242-007d4f00-4047-11eb-8029-5058e969902f.png)


This morning the task seemed to have worked.
I tested a download and everything seems to have indexed properly :-)
Thank you very much for your help this has been bothering me for so many years you have no ideas...

Danyfire

**Closed as completed** 2020-12-19 09:05 UTC
