### ISSUE TITLE
Error after upgrade

### ISSUE THREAD

**Issue by pmcl77** [letorbi/synoindexwatcher#38] opened 2020-07-30 11:09 UTC
Hi,

I am back :) I noticed my synoidexwatcher seemed to have stopped working around end of may (which I find strange since I have not changed anything)... now I wanted to upgrade to the latest version but when trying to start, I got the error:

`root@syno:~# python -m synoindexwatcher
2020-07-30 12:51:08,326 ERROR An uncaught exception occurred
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/synoindexwatcher/__main__.py", line 224, in <module>
    start()
  File "/usr/lib/python2.7/site-packages/synoindexwatcher/__main__.py", line 189, in start
    inotify = INotify()
  File "/usr/lib/python2.7/site-packages/inotifyrecursive/inotifyrecursive.py", line 31, in __init__
    inotify_simple.INotify.__init__(self)
  File "/usr/lib/python2.7/site-packages/inotify_simple.py", line 84, in __init__
    global _libc; _libc = _libc or CDLL(find_library('c'), use_errno=True)
  File "/usr/lib/python2.7/ctypes/util.py", line 242, in find_library
    raise RuntimeError("can not find library %s" % name)
RuntimeError: can not find library c`

Any idea what could be wrong?

Thanks,
Phil

**Comment by letorbi** [comment] 2020-07-30 19:57
Hej Phil,

it is really strange that your Synoindex Watcher installation stopped working by the end of May, because I haven't published any new releases since February. I've merged a pull-request (https://github.com/letorbi/synoindexwatcher/issues/35) in May though, but this should only affect you, if you've installed Synoindex Watcher directly from the GitHub repo. Do you have any logs that could explain, why your installation stopped working?

The error you are describing is most likely an upstream problem in one of the dependencies. The package *inotify-simple* changed its way to find the C standard library *libc.so*. The related issue is https://github.com/chrisjbillington/inotify_simple/issues/20 and the related commit https://github.com/chrisjbillington/inotify_simple/commit/a88bdb5df74588c31f76d7a069441a295daedee0.

I can reproduce the error with the latest version (1.3.4) of *inotify-simple*, but it is gone after a downgrade to version 1.3.3. As a workaround you could downgrade your version of  *inotify-simple* with the the following command:

```
$ sudo python -m pip install inotify-simple==1.3.3
```

It would be great if you could [create an issue in the inotify-simple repo](https://github.com/chrisjbillington/inotify_simple/issues). If you put a link to this issue here in the new issue you don't have to write much. Chris is very helpful and competent and I'm sure he'll fix the bug in no time :slightly_smiling_face: 

Bye,
Torben

PS: I'm leaving this issue open until the bug has been fixed upstream.

**Comment by pmcl77** [comment] 2020-07-30 20:24
Thanks Torben,

Could it be, that inotify-simple was upgraded automatically, or maybe along with some packages in the synology package center? Because I have not installed or upgraded anything else.

I tried the inotify-simple downgrade, but still get an error when. Though it also tries to add a path, that does not exist anymore (/volume1/music) and so maybe I am having some old installation that might be the problem?

Also, should I maybe not be using python 2.7 anymore?


`root@syno:~# sudo python -m pip install inotify-simple==1.3.3
DEPRECATION: Python 2.7 reached the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 is no longer maintained. pip 21.0 will drop support for Python 2.7 in January 2021. More details about Python 2 support in pip can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support
Collecting inotify-simple==1.3.3
  Downloading inotify_simple-1.3.3.tar.gz (9.4 kB)
Requirement already satisfied: enum34 in /usr/lib/python2.7/site-packages (from inotify-simple==1.3.3) (1.1.10)
Building wheels for collected packages: inotify-simple
  Building wheel for inotify-simple (setup.py) ... done
  Created wheel for inotify-simple: filename=inotify_simple-1.3.3-py2-none-any.whl size=7529 sha256=56390df9511a0e8378b28522a506c462b7ac72606537578b6ec2f9a7bc05dfcc
  Stored in directory: /root/.cache/pip/wheels/7a/ed/ab/34b180488fc0131f59dbacf99c4a709e4df6224fc2ddda16f3
Successfully built inotify-simple
Installing collected packages: inotify-simple
  Attempting uninstall: inotify-simple
    Found existing installation: inotify-simple 1.3.4
    Uninstalling inotify-simple-1.3.4:
      Successfully uninstalled inotify-simple-1.3.4
Successfully installed inotify-simple-1.3.3

root@syno:~# python -m synoindexwatcher
2020-07-30 22:20:18,505 INFO Adding watch for path: /volume1/music
2020-07-30 22:20:18,505 ERROR An uncaught exception occurred
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/synoindexwatcher/__main__.py", line 224, in <module>
    start()
  File "/usr/lib/python2.7/site-packages/synoindexwatcher/__main__.py", line 194, in start
    inotify.add_watch_recursive(path, mask, filter)
  File "/usr/lib/python2.7/site-packages/inotifyrecursive/inotifyrecursive.py", line 116, in add_watch_recursive
    return self.__add_watch_recursive(path, mask, filter, name, -1, False)
  File "/usr/lib/python2.7/site-packages/inotifyrecursive/inotifyrecursive.py", line 79, in __add_watch_recursive
    wd = inotify_simple.INotify.add_watch(self, path, mask | flags.IGNORED | flags.CREATE | flags.MOVED_FROM | flags.MOVED_TO)
  File "/usr/lib/python2.7/site-packages/inotify_simple.py", line 105, in add_watch
    return _libc_call(_libc.inotify_add_watch, self.fileno(), fsencode(path), mask)
  File "/usr/lib/python2.7/site-packages/inotify_simple.py", line 38, in _libc_call
    raise OSError(errno, strerror(errno))
OSError: [Errno 2] No such file or directory
root@syno:~# cat /usr/local/etc/synoindexwatcher.conf
[GLOBAL]
logfile=
loglevel=INFO

[/volume2/homes/phil/photo]

[/volume2/photo]
`

**Comment by pmcl77** [comment] 2020-07-30 20:44
I seem to have the following installations:

/usr/lib/python2.7/site-packages/synoindexwatcher

/volume1/@appstore/py3k/usr/local/lib/python3.5/site-packages/synoindexwatcher/

however in none of them I can find any reference to the invalid path volume1/music/.

So now, when I used the s99 script to start, it worked... I just wish I knew why it just stopped working.

**Comment by letorbi** [comment] 2020-07-31 10:58
Hej Phil,

as [mentioned in the README](https://github.com/letorbi/synoindexwatcher#usage) Synoindex Watcher will try to watch the paths */volume1/music*, */volume1/photo* and */volume1/video*, if no other paths have been passed via the command-line or a config-file. However, I will add some debug-output to make it clearer which paths will be watched and why.

If you start Synoindex Watcher via the init-script (*S99...*), Synoindex Watcher is probably started with the following command: `python -m synoindexwatcher --config /usr/local/etc/synoindexwatcher.conf`. This way Synoindex Watcher will try to watch the path in the config-file instead of the default ones.

The *synoindexwatcher* package. depends on the package *inotifyrecursive*, which depends on *inotify-simple*. So the *inotify-simple* package was probably installed along with the *synoindexwatcher* package. I cannot say exactly why *inotify-simple* was updated to 1.3.4. It might be due to some other package, but I find another scenario more likely:

You have two Python installations, version 2 and 3, and both installations maintain their own packages. I assume that your original installation of *synoindexwatcher* (and *inotify-simple*) was for Python 2. But now you've also installed it for Python 3 by accident and since Python 3 had no *inotify-simple* package yet, version 1.3.4 of it was installed.

I recommend to remove the *synoindexwatcher*, *inotifyrecursive* and *inotify-simple* packages from the Python 3 installation to avoid confusion. This can be done easily with the following command:

```
sudo python3 -m pip uninstall synoindexwatcher inotifyrecursive inotify-simple
```

If you have other packages installed for Python 3, you should check if one of them depends on *inotifyrecursive* or *inotify-simple*, but think this is quite unlikely.

I hope this answers your questions and helps to solve your problems.

Bye
Torben

PS: Have you [created an issue in the inotify-simple repo](https://github.com/chrisjbillington/inotify_simple/issues), already?

**Comment by letorbi** [comment] 2020-08-04 09:56
I've created an issue in the inotify-simple repo (https://github.com/chrisjbillington/inotify_simple/issues/21). Feel free to add your thoughts there as well :slightly_smiling_face: 

I've also created a new issue about adding the watched folder to the log output (#39).

**Comment by letorbi** [comment] 2020-08-10 08:35
The issue has been fixed upstream and #39 has been closed as well. So I'm closing this issue here, too.

**Closed as completed by letorbi** 2020-08-10 08:35 UTC

**Comment by pmcl77** [comment] 2020-08-10 14:08
Thanks Torben,

sorry for the late reply, I am quite busy hunting for a new job and a new appartment at the same time :)

**Comment by letorbi** [comment] 2020-08-10 17:09
No worries :)

**Comment by letorbi** [comment] 2020-08-10 17:14
No worries :) BTW: I've also created a new release (0.10.3).
